version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    networks:
      - sample-network

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - sample-network
    depends_on:
      - client

networks:
  sample-network:
    driver: bridge
